name: Data Update
on: workflow_dispatch
jobs:
  get_rss: 
    runs-on: ubuntu-latest
    name: Update All Data
    steps: 
      - name: Checkout
        uses: actions/checkout@v4.1.1  
        with:
          submodules: 'true'
      - name: RSS to JSON
        uses: I-Valchev/rss-to-json@1.0.0
        with: 
          source: .github/feeds.yaml
          target: _data/gmc-rss.json
      - name: Get RPL Price
        uses: fjogeleit/http-request-action@v1.14.2
        with: 
          url: "https://optimism-mainnet.infura.io/v3/${{ secrets.INFURA }}"
          data: '{"jsonrpc": "2.0", "id": 1, "method": "eth_call", "params": [{"to":"0xADE082c91A6AeCC86fC11704a830e933e1b382eA","data":"0x50d25bcd"}, "latest"]}'
          responseFile: _data/rpl-usd.json
      - name: Copy Source Data
        run: |
          # cp "_source/meta/dates.yml" "_data/dates.yml"
          # cp "_source/meta/contacts.yml" "_data/contacts.yml"
          cp -R "_source/bounties" "bounties"
          cp "_source/meta/bounty-faq.md" "docs/bounty-faq.md"
          cp "_source/meta/resources.md" "docs/resources.md"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with: 
          commit-message: Update data
          committer: GitHub <noreply@github.com>
          token: ${{ secrets.PAT }}
          branch: temp-data-updates
          delete-branch: true
          title: 'Update Data'
