name: Data Update
on: workflow_dispatch
jobs:
  get_rss: 
    runs-on: ubuntu-latest
    name: Get GMC Posts
    steps: 
      - name: Checkout
        uses: actions/checkout@v4.1.1  
        with:
          submodules: 'true'
      - name: RSS to JSON
        uses: I-Valchev/rss-to-json@1.0.0
      - name: Copy Result
        run: |
          ls
          cp "feeds.json" "./_data/gmc-rss.json"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with: 
          commit-message: Update data
          committer: GitHub <noreply@github.com>
          token: ${{ secrets.PAT }}
          branch: temp-data-updates
          delete-branch: true
          title: 'Update Data'
